apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: nano-idp
servers: 1
agents: 0
image: rancher/k3s:v1.28.5-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=cgroup-driver=systemd
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=eviction-hard=memory.available<200Mi
        nodeFilters:
          - server:*
  runtime:
    labels:
      - label: cgroupv2=enabled
        nodeFilters:
          - server:*
